
``` {r Init, echo=FALSE}
library(devtools) # Essential for Aurum integration
library(tidyverse)  # streamlining R coding since 2016

install_github('drkgyoung/Exeter_Diabetes_aurum_package') # Package created by Exeter University to work with CPRD data
library(aurum)

cprd = CPRDData$new(cprdEnv = "test-remote", cprdConf = '~/RStudio/aurum.yaml')
codesets = cprd$codesets()
codes = codesets$getAllCodeSetVersion(v = "31/10/2021")
```


``` {r Creating all_patid_raw_antibodies tables, echo=FALSE}
# Creation of all_patid_raw_gad, all_patid_raw_ia2 and all_patid_raw_ica
analysis = cprd$analysis("all_patid")

cprd$tables$observation %>%
    inner_join(codes$gad_abs, by="medcodeid") %>%
    analysis$cached("raw_gad", indexes=c("patid", "obsdate", "testvalue", "numunitid"))

cprd$tables$observation %>%
    inner_join(codes$ia2, by="medcodeid") %>%
    analysis$cached("raw_ia2", indexes=c("patid", "obsdate", "testvalue", "numunitid"))

cprd$tables$observation %>%
    inner_join(codes$ica, by="medcodeid") %>%
    analysis$cached("raw_ica", indexes=c("patid", "obsdate", "testvalue", "numunitid"))

```

``` {r Checking and cleaning GAD}
analysis = cprd$analysis("all_patid_raw")

# raw GAD table
ethan_raw_antibody = ethan_raw_antibody %>%
  analysis$cached("gad")

#> multi line comments!!

analysis = cprd$analysis("ethan_clean")
ethan_raw_antibody = ethan_raw_antibody %>%
  select(patid, obsdate, testvalue, numunitid, numrangelow, numrangehigh) %>%
  mutate( result = ifelse( 
                          !is.na(testvalue) & !is.na(numrangehigh),
                          ifelse(testvalue >= numrangehigh, 1, 0),
                          ifelse( #If either testvalue | numrangehigh == NA
                                  is.na(testvalue),
                                  0, # If testvalue = NA, interpreted as negative test
                                  ifelse( #Numrangehigh was the == NA, if value >11, then positive
                                          testvalue >= 11,
                                          1,
                                          0
                                        )
                                 ) 
                        )
         ) %>%
  analysis$cached("gad")
```


``` {r Cleaning and Preparing IA2}
analysis = cprd$analysis("all_patid_raw")

# raw IA2 table
ethan_raw_antibody = ethan_raw_antibody %>%
  analysis$cached("ia2")

#> multi line comments!!

analysis = cprd$analysis("ethan_clean")
ethan_raw_antibody = ethan_raw_antibody %>%
  select(patid, obsdate, testvalue, numunitid, numrangelow, numrangehigh) %>%
  mutate( result = ifelse( 
                          !is.na(testvalue) & !is.na(numrangehigh),
                          ifelse(testvalue >= numrangehigh, 1, 0),
                          ifelse( #If either testvalue | numrangehigh == NA
                                  is.na(testvalue),
                                  0, # If testvalue = NA, interpreted as negative test
                                  ifelse( #Numrangehigh was the == NA, if value >=7.5, then positive
                                          testvalue >= 7.5,
                                          1,
                                          0
                                        )
                                 ) 
                        )
         ) %>%
  analysis$cached("ia2")
```


``` {r Cleaning and Preparing ICA}

# [TODO] Find correct value range for ICA and create table

analysis = cprd$analysis("all_patid_raw")

# raw ICA table
ethan_raw_antibody = ethan_raw_antibody %>%
  analysis$cached("ica")

analysis = cprd$analysis("ethan_clean")
ethan_raw_antibody = ethan_raw_antibody %>%
  select(patid, obsdate, testvalue, numunitid, numrangelow, numrangehigh) %>%
  mutate( result = ifelse( 
                          !is.na(testvalue) & !is.na(numrangehigh),
                          ifelse(testvalue >= numrangehigh, 1, 0),
                          ifelse( #If either testvalue | numrangehigh == NA
                                  is.na(testvalue),
                                  0, # If testvalue = NA, interpreted as negative test
                                  ifelse( #Numrangehigh was the == NA, if value >=7.5, then positive
                                          testvalue >= 7.5,
                                          1,
                                          0
                                        )
                                 ) 
                        )
         ) %>%
  analysis$cached("ica")
```