---
title: "baseline"
author: "Ethan de Villiers"
date: "`r Sys.Date()`"
output: html_document
---

## Init
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}

library(devtools) # Essential for Aurum integration
library(tidyverse)  # streamlining R coding since 2016
library(r2r) # Used in Hashmaps later

install_github('drkgyoung/Exeter_Diabetes_aurum_package') # Package created by Exeter University to work with CPRD data
library(aurum)
```

``` {r cprd, include=FALSE}
cprd = CPRDData$new(cprdEnv = "test-remote", cprdConf = '~/RStudio/aurum.yaml')
analysis = cprd$analysis("ethan_atdiagnosis")
```

``` {r Pulling Datasets}
# Pull data from t1t2_cohort which we will add baseline biomarkers to
analysis = cprd$analysis("all")
t1t2_cohort = t1t2_cohort %>% 
  analysis$cached("t1t2_cohort") %>%
  cbind.data.frame()

# Pull BMI data
analysis = cprd$analysis("all_patid_clean")
bmi_data = bmi_data %>% 
  analysis$cached("bmi_medcodes") %>%
  cbind.data.frame()

#Cleaning/preparing datasets
bmi_data = bmi_data %>%
  mutate(patid = as.character(patid)) # Change to strings to ensure large int integrity
t1t2_cohort = t1t2_cohort %>%
  mutate(patid = as.character(patid)) # Change to strings to ensure large int integrity

t1t2_cohort$bmi_date = NA
t1t2_cohort$bmi = NA

# Obtain all Patient IDs from T1T2 cohort that we need to calculate baseline BMI
patid_list = t1t2_cohort$patid
```

## Pulling Biomarkers
biomarkers <- c("weight", "height", "bmi", "fastingglucose", "hdl", "triglyceride", "creatinine_blood", "ldl", "alt", "ast", "totalcholesterol", "dbp", "sbp", "acr", "albumin_blood", "bilirubin", "haematocrit", "haemoglobin", "pcr")
 - Keep HbA1c separate as processed differently
 
guide to hashmaps:
m <- hashmap()
insert(m, "user", "vgherard") # Modifies `m` in place
query(m, "user")
#> [1] "vgherard"

```{r Baseline BMI, results='hide', echo=FALSE}
# Obtain all Patient IDs from T1T2 cohort that we need to calculate baseline BMI
bmi_patid = patid_list

for (i in 1:length(bmi_patid)) { 
  date_diag = t1t2_cohort %>%
    filter(bmi_patid[i] == patid) %>%
    select(dm_diag_date_all) 
  
  date_diag = date_diag$dm_diag_date_all[1] # Extract pure value of date_diag
  print(paste('NEW Patient! Diag Date:', date_diag)) # Now have patient's diagnosis date
  
  # Now need to convert patient's BMI scores to a list
  bmi_list = bmi_data %>%
    filter(patid == bmi_patid[i]) %>%
    select(date)
  
  bmi_list = as.Date(bmi_list$date, format="%Y-%m-%d")
  
  # Skip over this iteration of loop if no BMI data
  if (length(bmi_list) == 0){
    print(paste('No BMI results for patient: ', patid_list[i]))
    patid_list = patid_list[patid_list != bmi_patid[i]]
    next 
  } 
  
  # Logging
  print(paste('number of BMI entries = ', length(bmi_list)))
  print(bmi_list)
  
  dates_and_differences = hashmap()
  
  for (x in 1:length(bmi_list)){
    individ_date_diff = difftime(bmi_list[x], date_diag, units="weeks")
    if (individ_date_diff >= -12 & individ_date_diff <= 6){
      print(paste('date is accepted! >-12 & <6, diff = ', individ_date_diff))
      # Date is more recent than 12 weeks before diagnosis, and more recent than 6 weeks after diagnosis
      #insert(dates_and_differences, key = )
      dates_and_differences[[bmi_list[x]]] = abs( individ_date_diff ) # Saves absolute difference
    }
  }
  
  
  # SIf patients does not have any valid BMI readings 12 weeks before or 6 weeks after diagnosis, skip iteration
  if (length(dates_and_differences) == 0){
    print('No acceptable dates! Skipping patient...')
    patid_list = patid_list[patid_list != bmi_patid[i]]
    next 
  } 
  
  
  dates = as.numeric(values(dates_and_differences)) # convert difftie object into DOUBLE type
  dates = sort(dates) # Order absolute values in ascending order
  
  print(paste('closest to diag date = ', dates[1], ' weeks difference!'))
  
  for (x in 1:length(dates_and_differences)){
    key = keys(dates_and_differences)[[x]]
    if (dates_and_differences[[key]] == dates[1]){
      print(paste('BMI Date match found in Hashmap. Date stored = ', as.character(key)))
      bmi_diag_date = as.character(key)
    }
  }
  
  bmi_value = bmi_data %>%
    filter(bmi_patid[i] == patid) %>%
    filter(date == bmi_diag_date)
  bmi_value = bmi_value$testvalue
  print(paste('Pulled bmi_value from patient according to hashmap date stored. BMI pulled = ', bmi_value))
  
  #Now have the correct diagnosis date: bmi_diag_date = BMI diagnosis date
  #And have the correct diagnosis value: bmi_value = BMI test result on said date
  t1t2_cohort = t1t2_cohort %>%
    mutate(bmi_date = ifelse(bmi_patid[i] == patid, bmi_diag_date, bmi_date)) %>%
    mutate(bmi = ifelse(bmi_patid[i] == patid, bmi_value, bmi))
  
  

  # Remove patID from original list without interrupting this for loop iteration as it BMI has been completed for this patient!
  patid_list = patid_list[patid_list != bmi_patid[i]]
}

```



```{r Pushing to MySQL }
analysis = cprd$analysis("ethan_atdiagnosis")

t1t2_cohort = t1t2_cohort %>%
  analysis$cached("V1_bmi")



```