---
title: "TSH Medcode list creation"
author: "Ethan de Villiers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, echo=FALSE}
library(rio)
library(stringr)
library(dplyr)
library(tidyverse)

search_terms = list("thyroid stimulating hormone", "tsh", "thyroid stimulating")
exclusion_terms = list("antibody", "antib")
```


``` {r Environment Setup, echo=FALSE}
# Importing PBCL dictionary
dictionary_path = '~/Downloads/CPRD_Read_SNOMED_PBCL.txt'
pbcl_dictionary <- import(dictionary_path)


# Alter column datatypes
pbcl_dictionary = pbcl_dictionary %>%
  mutate(SNOMED_CONCEPTID = as.character(SNOMED_CONCEPTID))

filepath = '~/Downloads/CPRDAurumMedical.txt'
Medcode_lookup <- import(filepath)
Medcode_lookup = Medcode_lookup %>%
  mutate(SnomedCTConceptId = as.character(SnomedCTConceptId))
  
# View(pbcl_dictionary)
# View(Medcode_lookup)
```


``` {r Preparing Codelist from PBCL}
# RegEx - Run and check results before continuing
tsh_results_raw  = pbcl_dictionary %>%
  filter( 
    str_detect(V2_TERM, regex(paste(search_terms, collapse = "|"), ignore_case = TRUE)) == TRUE |
    str_detect(V3_TERM, regex(paste(search_terms, collapse = "|"), ignore_case = TRUE)) == TRUE |
    str_detect(SNOMED_TERM, regex(paste(search_terms, collapse = "|"), ignore_case = TRUE)) == TRUE ) %>%
  filter( 
    !str_detect(V2_TERM, regex(paste(exclusion_terms, collapse = "|"), ignore_case = TRUE)) == TRUE |
    !str_detect(V3_TERM, regex(paste(exclusion_terms, collapse = "|"), ignore_case = TRUE)) == TRUE |
    !str_detect(SNOMED_TERM, regex(paste(exclusion_terms, collapse = "|"), ignore_case = TRUE)) == TRUE )

#Building a cleaner dataframe
regex_results = rbind.data.frame(
    tsh_results_raw %>% 
      select(V2_READ_CODE, V2_TERM) %>%
      mutate(Type = "V2_read") %>%
      rename("Codes" = "V2_READ_CODE") %>%
      rename("Terms" = "V2_TERM")
    ,
    tsh_results_raw %>% 
      select(V3_READ_CODE, V3_TERM) %>%
      mutate(Type = "V3_read") %>%
      rename("Codes" = "V3_READ_CODE") %>%
      rename("Terms" = "V3_TERM")
    ,
    tsh_results_raw %>% 
      select(SNOMED_CONCEPTID, SNOMED_TERM) %>%
      mutate(Type = "SNOMED") %>%
      rename("Codes" = "SNOMED_CONCEPTID") %>%
      rename("Terms"= "SNOMED_TERM")
  )

# Removing duplicates
regex_results = unique(regex_results, by = "Codes")

```

``` {r Viewing and Cleaning raw-codelist, echo=FALSE}
View(regex_results)


#> exclusion_codelist = list("46gk.", "Xab3o", "997861000000100", "904791000000105", "44SU.", "44kP.", "XaIas", "XaJ2h", "1017221000000103", "391403004", "1002911000000103", "407685005")

#> regex_results = regex_results %>% filter(!(Codes %in% exclusion_codelist))

# Removing unwanted codes
regex_results = regex_results %>%
  filter(Codes != "995841000000105" & Codes != "43Gu" & Codes != "54495009" & Codes != "43mQ." &
           Codes != "43mQ0" & Codes != "XaEO4" & Codes != "XaIoT" & Codes != "XaJOp" &
           Codes != "XabCz" & Codes != "1028611000000102" & Codes != "395037008" &
           Codes != "1004411000000104" & Codes != "911341000000100") %>% # Remove SNOMED TSH ~Antibody~ code
  filter(Codes != "408273009" & Codes != "1005531000000107" & Codes != "44MQ.") # Remove SNOMED TSH ~binding site inhibitors~
```

``` {r TSH Medcodes}
medcodelist_df = Medcode_lookup %>%
  mutate(read_code = substr(CleansedReadCode, 1, 5) ) %>%
  mutate(SnomedCTConceptId = as.character(SnomedCTConceptId)) %>%
  filter((read_code %in% regex_results$Codes) | (SnomedCTConceptId %in% regex_results$Codes)) %>%
  select(MedCodeId, Term)

medcodelist_df = unique(medcodelist_df, by = "MedCodeId")
```

``` {r Exporting data frames}
View(medcodelist_df)
write.table(medcodelist_df, "exeter_medcodelist_tsh.txt", quote=FALSE, sep = "\t", row.names=FALSE, col.names=TRUE)
```